name: SPPIFN
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pytorch
  - torchvision
  - torchaudio
  - numpy
  - matplotlib
  - scikit-learn
  - pandas
  - pillow
  - pip
